### PR TITLE
Add Yara 4 support

### PR DESCRIPTION
**Pull request by miguelxpn**
Yara 4 has some slight breaking API changes. This makes the library compatible with 4. The version we're using is 4.2.3.

## Testing
- Verify that the tests passes.

### CODE REVIEW

**Review by singerb — COMMENTED** [review]
From a C/C++ standpoint this looks fine, and should enable us to merge and deploy this, and then upgrade systems to Yara 4 and recompile. I haven't tested it though.

**Comment by snake66** [comment]
Don't see anything that should be controversial here. Looks good!

**Comment by macbre** [comment]
Yay! We will then - finally 🎉  - be able to compile `node-yara` locally on our laptops and run `npm ci` locally in root directory of `jetpack-backups`. Thanks for this one!

**Comment by macbre** [comment]
I'm wondering if we can use #5 to prebuild `node-yara` binaries (instead of forcing each `npm ci` run to compile it from the scratch).

**Comment by miguelxpn** [comment]
> #5

Nice, I missed this somehow! We probably can, and it might make the whole migration to yara 4 easier on production as well. I'll review it and research it more during this weekend, thanks for this!

**Review by snake66 — APPROVED** [review]
Looks good. 

There's a few things outside of the actual changeset you may want to look at in a later patch. E.g the `throw()` dynamic exception specifier is deprecated after C++11 (and removed in C++17), so you probably want `noexcept` instead.

**Comment by macbre** [comment]
@miguelxpn - what's the plan for the next steps here?

Are we going to create a release on GitHub? This will push a new version of the package to the `npm` repository and we can test the stuff on our sandboxes (and locally with the hope that it will finally build on MacOS 😉 ).

**Comment by miguelxpn** [comment]
> @miguelxpn - what's the plan for the next steps here?
> 
> Are we going to create a release on GitHub? This will push a new version of the package to the `npm` repository and we can test the stuff on our sandboxes (and locally with the hope that it will finally build on MacOS 😉 ).

Yep. I'll do that later today and then we can touch base if there's anything that goes wrong. Thanks again for the help!

**Pull request merged**
